# Generated by Django 6.0.5 on 2026-06-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user_date_of_birth_user_sex'),
        ('database', '0005_competitor_date_of_birth_competitor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='database.country'),
        ),
    ]
