# Generated by Django 6.0.5 on 2026-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_competitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other / Prefer not to say')], max_length=1, null=True),
        ),
    ]
