# Generated by Django 6.0.5 on 2026-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_competitor_date_of_birth_competitor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
