# Generated by Django 6.0.5 on 2026-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_competitor_email_competitor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_dial_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
