# Generated by Django 6.0.5 on 2026-06-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_country_phone_dial_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='crew',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_partner', to='database.competitor'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='cart_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_cart_model', to='database.cartmodel'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='engine_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_engine_model', to='database.enginemodel'),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engine_models', to='database.manufacturer'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_models', to='database.manufacturer'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='cart_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_cart_manufacturer', to='database.manufacturer'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='cell_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_cell_manufacturer', to='database.manufacturer'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='engine_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_engine_manufacturer', to='database.manufacturer'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='wing_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_wing_manufacturer', to='database.manufacturer'),
        ),
        migrations.CreateModel(
            name='ULMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ulm_models', to='database.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='cell_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_cell_model', to='database.ulmmodel'),
        ),
        migrations.CreateModel(
            name='WingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wing_models', to='database.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='wing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitors_as_wing_model', to='database.wingmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='enginemodel',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('manufacturer', 'name')},
        ),
    ]
