# Generated by Django 6.0.5 on 2026-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_cartmodel_enginemodel_manufacturer_competitor_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='aircraft_type',
            field=models.CharField(choices=[('PARAMOTOR', 'Paramotor'), ('MICROLIGHT', 'Microlight')], default='PARAMOTOR', max_length=20),
        ),
    ]
