# Generated by Django 6.0.5 on 2026-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_competitor_aircraft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='aircraft_class',
            field=models.CharField(blank=True, choices=[('PF1', 'PF1'), ('PL1', 'PL1'), ('PF2', 'PF2'), ('PL2', 'PL2'), ('TRIKE1', 'Trike 1'), ('TRIKE2', 'Trike 2'), ('MULTIAXIS1', 'Multiaxis 1'), ('MULTIAXIS2', 'Multiaxis 2'), ('AUTOGYRO1', 'Autogyro 1'), ('AUTOGYRO2', 'Autogyro 2')], max_length=20, null=True),
        ),
    ]
