# Generated by Django 6.0.5 on 2026-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_competitor_aircraft_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='crew_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='wing_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='wing_ptv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='wing_surface',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
