# Generated by Django 6.0.5 on 2026-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_competitor_crew_weight_competitor_wing_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='club',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='fai_licence_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='insurance_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitor',
            name='medical_certificate_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitor',
            name='national_licence_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
