# Generated by Django 5.2.13 on 2026-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_country_airfield_database_alignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airfield',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='airfield',
            old_name='long',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
